# Generated by Django 5.2.1 on 2025-06-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_engine', '0002_portfolio_avg_buy_price_transaction_ssymbol_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ssymbol',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='avg_buy_price',
        ),
    ]
