# Generated by Django 5.2.1 on 2025-06-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_engine', '0004_pendingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='limit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_category',
            field=models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit')], default='MARKET', max_length=6),
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='order_type',
            field=models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit')], default='MARKET', max_length=6),
        ),
    ]
