# Generated by Django 5.2.1 on 2025-06-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_engine', '0005_pendingorder_limit_price_transaction_order_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='side',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='', max_length=4),
        ),
    ]
