# Generated by Django 5.2.1 on 2025-06-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_engine', '0007_limitorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='limit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
